name: aehuman_app
description: An upgraded MVP of the Æ‑HUMAN habit coach app
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter